### PR TITLE
Pin APSW to a more recent version

### PR DESCRIPTION
**Pull request by bennybp**
Adds a pin to to relatively recent versions of APSW (issue #51), since we use `pragma` to enable foreign key stuff in sqlite

Closes issue #51

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* ~~[ ] Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bennybp** [comment]
@conda-forge-admin please rerender

**Review by loriab — APPROVED** [review]

**Comment by j-wags** [comment]
Thanks both for catching this and acting on it so quickly!

**Comment by mattwthompson** [comment]
This unfortunately doesn't fix the issue - since the earlier build is still online, environment solutions with i.e. 3.39.2.1 are still valid and out there in the wild.

Could you update the repodata to fix the existing builds? https://prefix.dev/blog/repodata_patching

**Comment by j-wags** [comment]
Yeah, seconding Matt here - the old build without the aspw constraint is being preferentially selected by the conda solver, and this has caused all our QCPortal-dependent CI to fail for the last few days. Could you put in a patch for those? [Here's](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/665/files) an example of what patching looks like, and I'm happy to screenshare with a QCF maintainer to open a patching PR.

**Comment by bennybp** [comment]
That sounds like a plan. I have never done a repodata patch, so any kind of help would definitely be appreciated!

**Comment by j-wags** [comment]
Great - I'll contact you directly to schedule a screenshare.

**Comment by j-wags** [comment]
Patching PR here: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/862

**Pull request merged**
