### PR TITLE
Python 3.10 (or noarch?)

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
@conda-forge/qcfractal rebuilding here in order to get a python 3.10 package for qcfractal.

Two questions:

- is that ok to remove the `1.4` upper bound on `sqlalchemy` or do you think it's a no go?
- could that package actually be `noarch`?

**Comment by bennybp** [comment]
@hadim sqlalchemy 1.4 is still probably a hard limit for this version. Not sure if this can be noarch or not.

I have been working on the next major version, so this version is pretty far behind. I would be very interested in talking to you about the improvements and changes in the next version (if you could email or message me!).

**Comment by hadim** [comment]
@bennybp thanks for the update here! We would love to hear more about the next major bump indeed. We'll contact you over email soon.

In the meantime, is it still possible to review and merge this one? The only thing we need here is simply the python 3.10 compatible package. Even if this version is old and to be replaced soon, we could still benefit from it.

**Comment by loriab** [comment]
The `next` branch that Ben mentioned is noarch https://anaconda.org/qcarchive/qcfractal/files, so that's coming. To be minimally invasive here at v0.15.8, he might merge https://github.com/conda-forge/qcfractal-feedstock/pull/37 instead. (fwiw, psi4 supports both v0.15.8 and `next`.)

**Comment by loriab** [comment]
Ok, the py310 package is up: https://anaconda.org/conda-forge/qcfractal/files

**Comment by hadim** [comment]
Thanks everyone!

**Pull request closed without merging**
