### PR TITLE
Requiring python >=3.7, numpy >=1.17

### PR DESCRIPTION
**Pull request by dotsdl**
Requiring python >=3.7, numpy >=1.17

See https://github.com/MolSSI/QCFractal/issues/659 for decision.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dotsdl** [comment]
@conda-forge-admin, please rerender

**Comment by dotsdl** [comment]
@conda-forge-admin, please rerender

**Comment by Lnaden** [comment]
Are you sure you want to *skip* builds for Python 3.7 when this is meant to be `>= py37`? If its just debugging, thats fine, but just checking.

**Comment by dotsdl** [comment]
@Lnaden the skip is for Python < 3.7, so 3.7 should be included here.

**Comment by dotsdl** [comment]
What is concerning to me is that for OSX we're still seeing a Python 3.6 build. Not sure what's going on there.

**Comment by dotsdl** [comment]
Nevermind, Python 3.6 Linux and OSX builds both skip in within their respective Azure Pipelines. This is consistent with our spec of `python >= 3.7` for the run requirements.

**Comment by Lnaden** [comment]
> Python < 3.7, so 3.7 should be included here.

A whoops, misread that. 

> we're still seeing a Python 3.6 build

I don't think they actually are. The build system is still checking against Python 3.6, but ultimately skips it, check here:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=291071&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00&l=904

The 3.6 OSX builds take about 4 min, and most of that is the setup and conda build precursor and staging a new build. Its slower than Linux since they cant use docker images. However, the 3.7+ builds are running for longer and the whole time. 

They probably do this as its easier to just trigger everything as normal and make sure it runs than try to check before it runs  (I've tried to do that, it sucks).

**Comment by dotsdl** [comment]
Default numpy will become 1.17 this month, so this will meet our numpy >= 1.17 requirement too: https://gitter.im/conda-forge/conda-forge.github.io?at=6050e7c3a3a2f04f1ffea789

**Comment by dotsdl** [comment]
Good to merge @Lnaden or @bennybp! This should get the changes in for the auto-PRs triggered by the new release, hopefully.

**Pull request merged**
