### PR TITLE
V12 multi-build update

### PR DESCRIPTION
**Pull request by dgasmith**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@loriab @mattwelborne @Lnaden A few change to start a multi-build, the `-core` isn't required now, but give us a place to start in the future. We can take it out for here as its not so useful.

### CODE REVIEW

**Comment by Lnaden** [comment]
So if I understand this right, this will make 3 packages:

* `qcfractal-core`,
* `qcfractal`
* `qcfractal-dashboard`

I like the idea and I think the assembly is mostly right, but I have a few questions:

1. Who is `-core` for? If there are not really users for this, then we should make the +dashly build the "core" by dropping the `core` build entirely. I'm sure there are users, but I just wanted to make sure we have them enumerated/listed
2. Assuming there is the `-core` base of users and that is in fact most users, then do we want to recommend downstream packages start requiring`qcfractal-core` as a dep instead of `qcfractal`?
3. Finally, you have removed the  `qcfractal-dashboard`  entry point for the ` `qcfractal-core`  and ` `qcfractal`  builds which I agree with, but it has not been re-added to the `qcfractal-dashboard` build. I'm not exactly sure how to do that, but I do know that omitting entry points causes problems in playing nice with `conda`, is there a way to get that back in for just `qcfractal-dashboard`?

**Comment by dgasmith** [comment]
1) Core is for additional downstream packages only `qcfractal-parsl` `qcfractal-xxx`.
2) See above.
3) `qcfractal-server dashboard` is the new entry point for the dashboard.

**Comment by dgasmith** [comment]
@conda-forge-admin, please rerender

**Comment by dgasmith** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
